# Generated by Django 5.2.8 on 2025-11-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='users.tutor'),
        ),
        migrations.AddField(
            model_name='tutorsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.subject'),
        ),
        migrations.AddField(
            model_name='tutorsubject',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.tutor'),
        ),
        migrations.AlterUniqueTogether(
            name='tutorsubject',
            unique_together={('tutor', 'subject')},
        ),
    ]
