# Generated by Django 5.2.8 on 2025-11-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.subject'),
        ),
    ]
