# Generated by Django 5.2.8 on 2025-11-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='users.student'),
        ),
        migrations.AddField(
            model_name='rating',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.tutor'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('student', 'tutor', 'booking')},
        ),
    ]
